import { config } from "dotenv";
import { db } from "./index.js";
import { foodItems } from "./schema.js";

config();

const daysFromNow = (days: number) => {
	const d = new Date();
	d.setDate(d.getDate() + days);
	return d;
};

const seedData = [
	{
		name: "Organic Bananas",
		description: "Fresh organic bananas from local farm",
		category: "Fruits",
		quantity: 6,
		unit: "pieces",
		calories: 105,
		protein: 1.3,
		carbs: 27.0,
		fat: 0.4,
		expirationDate: new Date("2025-01-15"),
	},
	{
		name: "Greek Yogurt",
		description: "Plain Greek yogurt, high in protein",
		category: "Dairy",
		quantity: 1,
		unit: "container",
		calories: 130,
		protein: 20.0,
		carbs: 9.0,
		fat: 0.0,
		expirationDate: new Date("2025-01-10"),
	},
	{
		name: "Whole Wheat Bread",
		description: "Artisan whole wheat sourdough bread",
		category: "Grains",
		quantity: 1,
		unit: "loaf",
		calories: 80,
		protein: 4.0,
		carbs: 15.0,
		fat: 1.0,
		expirationDate: new Date("2025-01-08"),
	},
	{
		name: "Chicken Breast",
		description: "Boneless, skinless chicken breast",
		category: "Protein",
		quantity: 2,
		unit: "lbs",
		calories: 165,
		protein: 31.0,
		carbs: 0.0,
		fat: 3.6,
		expirationDate: new Date("2025-01-05"),
	},
	{
		name: "Baby Spinach",
		description: "Fresh baby spinach leaves",
		category: "Vegetables",
		quantity: 1,
		unit: "bag",
		calories: 7,
		protein: 0.9,
		carbs: 1.1,
		fat: 0.1,
		expirationDate: new Date("2025-01-07"),
	},
	{
		name: "Almonds",
		description: "Raw unsalted almonds",
		category: "Nuts",
		quantity: 1,
		unit: "bag",
		calories: 164,
		protein: 6.0,
		carbs: 6.1,
		fat: 14.2,
		expirationDate: new Date("2025-06-01"),
	},
	{
		name: "Olive Oil",
		description: "Extra virgin olive oil",
		category: "Oils",
		quantity: 1,
		unit: "bottle",
		calories: 884,
		protein: 0.0,
		carbs: 0.0,
		fat: 100.0,
		expirationDate: new Date("2026-01-01"),
	},
	{
		name: "Brown Rice",
		description: "Long grain brown rice",
		category: "Grains",
		quantity: 2,
		unit: "lbs",
		calories: 216,
		protein: 5.0,
		carbs: 45.0,
		fat: 1.8,
		expirationDate: new Date("2025-12-01"),
	},
	{
		name: "Cheddar Cheese",
		description: "Sharp cheddar cheese block",
		category: "Dairy",
		quantity: 1,
		unit: "block",
		calories: 113,
		protein: 7.0,
		carbs: 1.0,
		fat: 9.0,
		expirationDate: new Date("2025-02-15"),
	},
	{
		name: "Avocados",
		description: "Ripe Hass avocados",
		category: "Fruits",
		quantity: 3,
		unit: "pieces",
		calories: 234,
		protein: 2.9,
		carbs: 12.0,
		fat: 21.0,
		expirationDate: new Date("2025-01-06"),
	},
	{
		name: "Strawberries",
		description: "Fresh strawberries",
		category: "Fruits",
		quantity: 1,
		unit: "container",
		calories: 32,
		protein: 0.7,
		carbs: 7.7,
		fat: 0.3,
		createdAt: daysFromNow(-6),
		expirationDate: daysFromNow(2),
	},
	{
		name: "Blueberries",
		description: "Wild blueberries",
		category: "Fruits",
		quantity: 1,
		unit: "pint",
		calories: 57,
		protein: 0.7,
		carbs: 14.5,
		fat: 0.3,
		createdAt: daysFromNow(-5),
		expirationDate: daysFromNow(3),
	},
	{
		name: "Kale",
		description: "Organic curly kale",
		category: "Vegetables",
		quantity: 1,
		unit: "bunch",
		calories: 33,
		protein: 2.9,
		carbs: 6.7,
		fat: 0.6,
		createdAt: daysFromNow(-4),
		expirationDate: daysFromNow(4),
	},
	{
		name: "Bell Peppers",
		description: "Mixed red and yellow bell peppers",
		category: "Vegetables",
		quantity: 3,
		unit: "pieces",
		calories: 31,
		protein: 1.0,
		carbs: 6.0,
		fat: 0.3,
		createdAt: daysFromNow(-3),
		expirationDate: daysFromNow(5),
	},
	{
		name: "Salmon Fillet",
		description: "Fresh Atlantic salmon",
		category: "Protein",
		quantity: 1,
		unit: "lb",
		calories: 208,
		protein: 22.0,
		carbs: 0.0,
		fat: 13.0,
		createdAt: daysFromNow(-2),
		expirationDate: daysFromNow(1),
	},
	{
		name: "Ground Turkey",
		description: "Lean ground turkey",
		category: "Protein",
		quantity: 1,
		unit: "lb",
		calories: 170,
		protein: 22.0,
		carbs: 0.0,
		fat: 9.0,
		createdAt: daysFromNow(-1),
		expirationDate: daysFromNow(2),
	},
	{
		name: "Whole Milk",
		description: "Organic whole milk",
		category: "Dairy",
		quantity: 1,
		unit: "gallon",
		calories: 149,
		protein: 7.7,
		carbs: 11.7,
		fat: 8.0,
		createdAt: daysFromNow(-3),
		expirationDate: daysFromNow(6),
	},
	{
		name: "Eggs",
		description: "Free-range large eggs",
		category: "Protein",
		quantity: 12,
		unit: "pieces",
		calories: 72,
		protein: 6.3,
		carbs: 0.4,
		fat: 4.8,
		createdAt: daysFromNow(-5),
		expirationDate: daysFromNow(7),
	},
	{
		name: "Sourdough Bread",
		description: "Fresh-baked sourdough loaf",
		category: "Grains",
		quantity: 1,
		unit: "loaf",
		calories: 188,
		protein: 7.7,
		carbs: 36.5,
		fat: 1.2,
		createdAt: daysFromNow(-2),
		expirationDate: daysFromNow(4),
	},
	{
		name: "Cherry Tomatoes",
		description: "Vine-ripened cherry tomatoes",
		category: "Vegetables",
		quantity: 1,
		unit: "pint",
		calories: 27,
		protein: 1.3,
		carbs: 5.8,
		fat: 0.3,
		createdAt: daysFromNow(-4),
		expirationDate: daysFromNow(3),
	},
	{
		name: "Cucumber",
		description: "English cucumber",
		category: "Vegetables",
		quantity: 2,
		unit: "pieces",
		calories: 16,
		protein: 0.7,
		carbs: 3.6,
		fat: 0.1,
		createdAt: daysFromNow(-6),
		expirationDate: daysFromNow(5),
	},
	{
		name: "Hummus",
		description: "Roasted red pepper hummus",
		category: "Snacks",
		quantity: 1,
		unit: "container",
		calories: 166,
		protein: 7.9,
		carbs: 14.3,
		fat: 9.6,
		createdAt: daysFromNow(-1),
		expirationDate: daysFromNow(7),
	},
	{
		name: "Carrots",
		description: "Organic baby carrots",
		category: "Vegetables",
		quantity: 1,
		unit: "bag",
		calories: 41,
		protein: 0.9,
		carbs: 9.6,
		fat: 0.2,
		createdAt: daysFromNow(-7),
		expirationDate: daysFromNow(6),
	},
	{
		name: "Apples",
		description: "Honeycrisp apples",
		category: "Fruits",
		quantity: 5,
		unit: "pieces",
		calories: 95,
		protein: 0.5,
		carbs: 25.0,
		fat: 0.3,
		createdAt: daysFromNow(-3),
		expirationDate: daysFromNow(7),
	},
	{
		name: "Mozzarella",
		description: "Fresh mozzarella ball",
		category: "Dairy",
		quantity: 1,
		unit: "ball",
		calories: 85,
		protein: 6.3,
		carbs: 0.6,
		fat: 6.3,
		createdAt: daysFromNow(-2),
		expirationDate: daysFromNow(3),
	},
	{
		name: "Pasta",
		description: "Whole wheat penne pasta",
		category: "Grains",
		quantity: 1,
		unit: "box",
		calories: 174,
		protein: 7.5,
		carbs: 37.0,
		fat: 0.8,
		createdAt: daysFromNow(-5),
		expirationDate: daysFromNow(7),
	},
	{
		name: "Tofu",
		description: "Extra firm organic tofu",
		category: "Protein",
		quantity: 1,
		unit: "block",
		calories: 144,
		protein: 17.0,
		carbs: 2.8,
		fat: 8.7,
		createdAt: daysFromNow(0),
		expirationDate: daysFromNow(5),
	},
	{
		name: "Lemons",
		description: "Fresh Meyer lemons",
		category: "Fruits",
		quantity: 4,
		unit: "pieces",
		calories: 17,
		protein: 0.6,
		carbs: 5.4,
		fat: 0.2,
		createdAt: daysFromNow(-4),
		expirationDate: daysFromNow(6),
	},
	{
		name: "Mushrooms",
		description: "Sliced cremini mushrooms",
		category: "Vegetables",
		quantity: 1,
		unit: "container",
		calories: 22,
		protein: 3.1,
		carbs: 3.3,
		fat: 0.3,
		createdAt: daysFromNow(-2),
		expirationDate: daysFromNow(2),
	},
	{
		name: "Orange Juice",
		description: "Fresh-squeezed orange juice",
		category: "Beverages",
		quantity: 1,
		unit: "carton",
		calories: 112,
		protein: 1.7,
		carbs: 25.8,
		fat: 0.5,
		createdAt: daysFromNow(-1),
		expirationDate: daysFromNow(4),
	},
];

async function seed() {
	try {
		console.log("🌱 Seeding database...");

		// Clear existing data
		await db.delete(foodItems);
		console.log("🗑️  Cleared existing food items");

		// Insert seed data
		await db.insert(foodItems).values(seedData);
		console.log(`✅ Inserted ${seedData.length} food items`);

		console.log("🎉 Seeding completed successfully!");
	} catch (error) {
		console.error("❌ Error seeding database:", error);
		process.exit(1);
	} finally {
		process.exit(0);
	}
}

seed();
